version: '3'

services:
  dropunit-simulator:
    build: ../containers/dropunit-simulator
    image: dropunit-simulator
    container_name: dropunit-simulator
    volumes:
      - ../../drop-unit-simulator:/application
    ports:
    - "9070:9070"
    - "9071:9071"
    networks:
      static-network:
        ipv4_address: 172.20.0.13

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/24
