server:
  applicationConnectors:
  - type: http
    port: 9070
  adminConnectors:
  - type: http
    port: 9071

logging:
   loggers:
     "net.lisanza":
       level: DEBUG
       additive: false
       appenders:
        - type: file
          currentLogFilename: logs/dropunit-simulator.log
          archivedLogFilenamePattern: logs/dropunit-simulator-%d.log.gz
          archivedFileCount: 5
          timeZone: UTC
        - type: console
          target: stderr
     "net.lisanza.dropunit.simulator.logging":
       level: DEBUG
       additive: false
       appenders:
         - type: file
           currentLogFilename: ./logs/dropunit-payload.log
           archivedLogFilenamePattern: ./logs/dropunit-payload-%d.log.gz
           archivedFileCount: 5
           timeZone: UTC
         - type: console
           target: stderr
